### ISSUE TITLE
Certain published npm module version numbers reset

### ISSUE THREAD

**Issue by pe8ter** [Microsoft/types-publisher#205]
Certain published typing module version numbers have reset back to 0.0.0 and are counting up from there. For example [@types/node](https://www.npmjs.com/package/@types/node) is now at 0.0.2 where not too long ago it was at 6.0.51.

I'd expect its version to still be in the 6.x range.

**Comment by andy-ms** [comment]
Fixed by https://github.com/Microsoft/types-publisher/pull/209

**Comment by IdeaHunter** [comment]
@andy-ms Im still experience the same problem with [@types/sharepoint](https://www.npmjs.com/package/@types/sharepoint): the latest commit merged 2 days ago DefinitelyTyped/DefinitelyTyped#13335, npm show current version as `0.0.0` - but the latest one according to semver should be `2013.0.31`.
